"""adding phone field

Revision ID: 136e30ae9ce7
Revises: efed50cd6236
Create Date: 2023-02-21 20:59:05.681630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136e30ae9ce7'
down_revision = 'efed50cd6236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('phone', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'message', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='unique')
    op.drop_column('message', 'phone')
    # ### end Alembic commands ###
